// content/content.js
// Runs on ChatGPT and Claude pages
// Detects AI responses and injects verification UI

// ── Detect which site we are on ───────────────────────────────────────────────
const SITE = {
  isChatGPT:
    window.location.hostname.includes("chatgpt.com") ||
    window.location.hostname.includes("chat.openai.com"),
  isClaude: window.location.hostname.includes("claude.ai"),
  isGemini: window.location.hostname.includes("gemini.google.com"),
};

console.log("LLM Checker loaded on:", window.location.hostname);
console.log("Is ChatGPT:", SITE.isChatGPT);
console.log("Is Claude:", SITE.isClaude);
console.log("Is Gemini:", SITE.isGemini);

// ── Auto-check setting (loaded from storage, updated via onChanged) ───────────
let autoCheckEnabled = false;

// ── Page-load guard — prevents auto-checking responses that existed on load ───
let pageLoadComplete = false;

// ── Selectors — multiple fallbacks for each platform ─────────────────────────
const SELECTORS = {
  chatgpt: [
    '[data-message-author-role="assistant"] .markdown',
    '[data-message-author-role="assistant"] .prose',
    '[data-message-author-role="assistant"]',
    ".agent-turn .prose",
    ".agent-turn",
    '[class*="assistant"] .markdown',
    '[class*="Message"] .markdown',
  ],
  claude: [
    // Current Claude.ai DOM (2025)
    '[data-testid="assistant-message"] .prose',
    '[data-testid="assistant-message"]',
    ".font-claude-message",
    '[class*="font-claude"]',
    '[class*="assistant-message"]',
    // Fallbacks for older or alternate Claude layouts
    '[class*="AssistantMessage"]',
    '[class*="assistant"] .prose',
    ".prose-base",
  ],
  gemini: [
    // Gemini (gemini.google.com) response containers
    ".model-response-text",
    "message-content",
    ".response-container-scrollable .response-content",
    "[data-response-id]",
    ".chat-history .model-response",
    '[class*="response-text"]',
    '[class*="model-response"]',
  ],
};

// ── Create the verify button ──────────────────────────────────────────────────
function createVerifyButton() {
  const btn = document.createElement("button");
  btn.className = "llm-checker-btn";
  btn.innerHTML = `
    <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
      <path d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"/>
    </svg>
    Cross-Check
  `;
  return btn;
}

// ── Create loading panel ──────────────────────────────────────────────────────
function createLoadingPanel() {
  const panel = document.createElement("div");
  panel.className = "llm-checker-panel loading";
  panel.innerHTML = `
    <div class="llm-checker-header">
      <span class="llm-checker-logo">🔍</span>
      <span>Cross-checking across AI models...</span>
    </div>
    <div class="llm-checker-loading">
      <div class="llm-checker-spinner"></div>
      <span>Querying multiple AI models simultaneously</span>
    </div>
  `;
  return panel;
}

// ── Format results as plain text for clipboard export ────────────────────────
function buildReport(data) {
  const { results, overall, sources } = data;
  const divider = "─".repeat(40);
  const ts = new Date().toLocaleString();
  const lines = [];

  lines.push("🔍 LLM Cross-Checker Report");
  lines.push(`Generated: ${ts}`);
  lines.push(divider);
  lines.push("");
  lines.push(`OVERALL VERDICT: ${overall.verdict}`);
  lines.push(`Confidence: ${overall.confidence}%`);
  lines.push(`Assessment: ${overall.message}`);

  if (sources?.length) {
    lines.push("");
    lines.push(divider);
    lines.push("SOURCES");
    sources.forEach((s, i) => {
      lines.push(`${i + 1}. ${s.title}`);
      lines.push(`   ${s.url}`);
      if (s.snippet) lines.push(`   ${s.snippet}`);
    });
  }

  lines.push("");
  lines.push(divider);
  lines.push("MODEL ASSESSMENTS");

  results.forEach((r) => {
    lines.push("");
    if (r.locked) {
      lines.push(`${r.model} — 🔒 Pro Only`);
      return;
    }
    if (r.error && !r.locked) {
      lines.push(`${r.model} — ERROR: ${r.error}`);
      return;
    }
    const v = r.result;
    lines.push(
      `${r.model} — ${v.verdict.replace(/_/g, " ")} (${v.confidence}% confident)`,
    );
    lines.push(`Summary: ${v.summary}`);
    if (v.bias_detected) lines.push(`Bias: ${v.bias_description}`);
    if (v.issues?.length) {
      lines.push("Issues:");
      v.issues.forEach((issue) => lines.push(`  • ${issue}`));
    }
    if (v.missing_context?.length) {
      lines.push("Missing context:");
      v.missing_context.forEach((ctx) => lines.push(`  • ${ctx}`));
    }
    if (v.flagged_claims?.length) {
      lines.push(`Flagged claims: ${v.flagged_claims.join(" | ")}`);
    }
  });

  lines.push("");
  lines.push(divider);
  lines.push(
    `Checked ${results.filter((r) => !r.error && !r.locked).length} of ${results.length} models`,
  );
  lines.push("Generated by LLM Cross-Checker — https://llm-crosschecker.com");

  return lines.join("\n");
}

// ── Create results panel ──────────────────────────────────────────────────────
function createResultsPanel(data) {
  const { results, overall, plan, usage, sources, topic } = data;
  const panel = document.createElement("div");
  panel.className = "llm-checker-panel";

  const modelResults = results
    .map((r) => {
      // Locked model (free tier)
      if (r.locked) {
        return `
        <div class="llm-checker-model locked">
          <div class="llm-checker-model-header">
            <span class="llm-checker-model-name">${r.model}</span>
            <span class="llm-checker-model-verdict" style="color:#8b949e;">🔒 Pro Only</span>
          </div>
          <div class="llm-checker-model-summary" style="color:#8b949e;">
            Upgrade to Pro to unlock this model
          </div>
        </div>`;
      }

      // API error
      if (r.error && !r.locked) {
        return `
        <div class="llm-checker-model error">
          <div class="llm-checker-model-header">
            <span class="llm-checker-model-name">${r.model}</span>
            <span class="llm-checker-model-verdict" style="color:#f85149;">API Error</span>
          </div>
          <div class="llm-checker-model-summary" style="color:#8b949e;">${r.error}</div>
        </div>`;
      }

      const v = r.result;
      const verdictColor =
        {
          ACCURATE: "#3fb950",
          PARTIALLY_ACCURATE: "#d29922",
          INACCURATE: "#f85149",
          UNVERIFIABLE: "#8b949e",
        }[v.verdict] || "#8b949e";

      const issuesList = v.issues?.length
        ? v.issues.map((i) => `<li>${i}</li>`).join("")
        : "";
      const contextList = v.missing_context?.length
        ? v.missing_context.map((c) => `<li>${c}</li>`).join("")
        : "";

      const claimTags =
        v.flagged_claims?.length
          ? `<div class="llm-checker-claims">
              <span class="llm-checker-claims-label">Flagged in text:</span>
              ${v.flagged_claims
                .map(
                  (c) =>
                    `<span class="llm-checker-claim-tag" style="border-color:${verdictColor}">${c}</span>`,
                )
                .join("")}
            </div>`
          : "";

      return `
      <div class="llm-checker-model">
        <div class="llm-checker-model-header">
          <span class="llm-checker-model-name">${r.model}</span>
          <span class="llm-checker-model-verdict" style="color:${verdictColor}">
            ${v.verdict.replace(/_/g, " ")}
          </span>
          <span class="llm-checker-confidence">${v.confidence}% confident</span>
        </div>
        <div class="llm-checker-model-summary">${v.summary}</div>
        ${v.bias_detected ? `<div class="llm-checker-bias">⚠️ Bias: ${v.bias_description}</div>` : ""}
        ${issuesList ? `<ul class="llm-checker-issues">${issuesList}</ul>` : ""}
        ${contextList ? `<div class="llm-checker-context"><strong>Missing context:</strong><ul>${contextList}</ul></div>` : ""}
        ${claimTags}
      </div>`;
    })
    .join("");

  // Usage bar for free users
  const usageBar =
    plan === "free" && usage?.checksLimit
      ? `
    <div class="llm-checker-usage-bar">
      <span>${usage.checksUsed}/${usage.checksLimit} free checks used this month</span>
      <a href="#" class="llm-checker-upgrade-link" id="upgradeLink">Upgrade to Pro</a>
    </div>`
      : "";

  const sourcesHtml = sources?.length
    ? `<div class="llm-checker-sources">
        <div class="llm-checker-sources-title">Sources used for fact-checking</div>
        ${sources
          .map(
            (s) => `
          <a class="llm-checker-source-item" href="${s.url}" target="_blank" rel="noopener noreferrer">
            <span class="llm-checker-source-title">${s.title}</span>
            <span class="llm-checker-source-snippet">${s.snippet}</span>
            <span class="llm-checker-source-url">${s.url}</span>
          </a>`,
          )
          .join("")}
      </div>`
    : "";

  panel.innerHTML = `
    <div class="llm-checker-header">
      <span class="llm-checker-logo">🔍</span>
      <span class="llm-checker-title">LLM Cross-Checker Results</span>
      ${topic ? `<span class="llm-checker-topic-badge llm-checker-topic-${topic}">${topic}</span>` : ""}
      <button class="llm-checker-close">✕</button>
    </div>

    <div class="llm-checker-overall" style="border-left: 4px solid ${overall.color}">
      <div class="llm-checker-verdict" style="color: ${overall.color}">
        ${overall.verdict}
      </div>
      <div class="llm-checker-verdict-msg">${overall.message}</div>
      <div class="llm-checker-avg-confidence">
        Average confidence: ${overall.confidence}%
        <div class="llm-checker-conf-bar">
          <div class="llm-checker-conf-fill"
               style="width:${overall.confidence}%; background:${overall.color}">
          </div>
        </div>
      </div>
    </div>

    ${sourcesHtml}

    <div class="llm-checker-models">
      <div class="llm-checker-models-title">Individual Model Assessments</div>
      ${modelResults}
    </div>

    ${usageBar}

    <div class="llm-checker-footer">
      <span>
        Checked ${results.filter((r) => !r.error && !r.locked).length} of ${results.length} models
        ${plan === "free" ? ' — <a href="#" id="upgradeFooter" style="color:#58a6ff;">Upgrade for all 6 models</a>' : ""}
      </span>
      <button class="llm-checker-copy-btn" id="copyReportBtn">
        <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
          <rect x="9" y="9" width="13" height="13" rx="2" ry="2"></rect>
          <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path>
        </svg>
        Copy Report
      </button>
    </div>
  `;

  // Close button
  panel.querySelector(".llm-checker-close").addEventListener("click", () => {
    panel.remove();
  });

  // Upgrade links open payment page
  panel.querySelectorAll("#upgradeLink, #upgradeFooter").forEach((el) => {
    el?.addEventListener("click", (e) => {
      e.preventDefault();
      chrome.runtime.sendMessage({ type: "OPEN_PAYMENT" });
    });
  });

  // Copy report to clipboard
  const copyBtn = panel.querySelector("#copyReportBtn");
  copyBtn?.addEventListener("click", () => {
    const report = buildReport(data);
    navigator.clipboard.writeText(report).then(
      () => {
        copyBtn.textContent = "✓ Copied!";
        copyBtn.classList.add("llm-checker-copy-btn--success");
        setTimeout(() => {
          copyBtn.innerHTML = `
            <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
              <rect x="9" y="9" width="13" height="13" rx="2" ry="2"></rect>
              <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path>
            </svg>
            Copy Report`;
          copyBtn.classList.remove("llm-checker-copy-btn--success");
        }, 2000);
      },
      () => {
        // Fallback for environments where clipboard API is blocked
        const ta = document.createElement("textarea");
        ta.value = report;
        ta.style.position = "fixed";
        ta.style.opacity = "0";
        document.body.appendChild(ta);
        ta.select();
        document.execCommand("copy");
        document.body.removeChild(ta);
        copyBtn.textContent = "✓ Copied!";
        setTimeout(() => {
          copyBtn.innerHTML = `
            <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
              <rect x="9" y="9" width="13" height="13" rx="2" ry="2"></rect>
              <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path>
            </svg>
            Copy Report`;
        }, 2000);
      },
    );
  });

  return panel;
}

// ── Create limit reached panel ────────────────────────────────────────────────
function createLimitPanel(response) {
  const panel = document.createElement("div");
  panel.className = "llm-checker-limit-panel";
  panel.innerHTML = `
    <div class="llm-checker-limit-icon">🔒</div>
    <div class="llm-checker-limit-title">Free limit reached</div>
    <div class="llm-checker-limit-msg">${response.message}</div>
    <div class="llm-checker-limit-usage">
      ${response.checksUsed}/${response.checksLimit} checks used this month
    </div>
    <button class="llm-checker-upgrade-btn" id="limitUpgradeBtn">
      ⚡ Upgrade to Pro — $4.99/month
    </button>
    <div style="font-size:11px;color:#8b949e;margin-top:8px;">
      Or bring your own API keys for $1.99/month
    </div>
  `;

  panel.querySelector("#limitUpgradeBtn").addEventListener("click", () => {
    chrome.runtime.sendMessage({ type: "OPEN_PAYMENT" });
  });

  return panel;
}

// ── Highlight a single phrase inside a DOM element ───────────────────────────
function highlightTextInElement(el, phrase, className) {
  if (!phrase || phrase.trim().length < 5) return null;

  const walker = document.createTreeWalker(el, NodeFilter.SHOW_TEXT, {
    acceptNode(node) {
      const tag = node.parentElement?.tagName?.toLowerCase();
      if (["code", "pre", "script", "style"].includes(tag)) {
        return NodeFilter.FILTER_REJECT;
      }
      return NodeFilter.FILTER_ACCEPT;
    },
  });

  const lowerPhrase = phrase.toLowerCase();
  let node;
  while ((node = walker.nextNode())) {
    const text = node.textContent;
    const idx = text.toLowerCase().indexOf(lowerPhrase);
    if (idx === -1) continue;

    const mark = document.createElement("mark");
    mark.className = className;
    mark.textContent = text.slice(idx, idx + phrase.length);

    const frag = document.createDocumentFragment();
    if (idx > 0) frag.appendChild(document.createTextNode(text.slice(0, idx)));
    frag.appendChild(mark);
    const after = text.slice(idx + phrase.length);
    if (after) frag.appendChild(document.createTextNode(after));

    node.parentNode.replaceChild(frag, node);
    return mark;
  }
  return null;
}

// ── Highlight all flagged claims from all model results ───────────────────────
function highlightClaims(responseEl, results) {
  const redClaims = new Set();
  const yellowClaims = new Set();

  results.forEach((r) => {
    if (!r.result?.flagged_claims) return;
    r.result.flagged_claims.forEach((claim) => {
      if (typeof claim !== "string" || claim.trim().length < 5) return;
      if (r.result.verdict === "INACCURATE") {
        redClaims.add(claim.trim());
      } else if (r.result.verdict === "PARTIALLY_ACCURATE") {
        yellowClaims.add(claim.trim());
      }
    });
  });

  const marks = [];

  redClaims.forEach((claim) => {
    const mark = highlightTextInElement(
      responseEl,
      claim,
      "llm-checker-highlight-red",
    );
    if (mark) marks.push(mark);
  });

  yellowClaims.forEach((claim) => {
    if (redClaims.has(claim)) return;
    const mark = highlightTextInElement(
      responseEl,
      claim,
      "llm-checker-highlight-yellow",
    );
    if (mark) marks.push(mark);
  });

  return marks;
}

// ── Remove all highlights inserted by highlightClaims ────────────────────────
function clearHighlights(marks) {
  marks.forEach((mark) => {
    const parent = mark.parentNode;
    if (!parent) return;
    parent.replaceChild(document.createTextNode(mark.textContent), mark);
    parent.normalize();
  });
}

// ── Core verify logic — shared by button click and auto-check ────────────────
function runVerify(responseEl, wrapper, btn, isAuto) {
  // Extract text from response
  let text = "";
  const markdownEl = responseEl.querySelector(
    '.markdown, .prose, [class*="markdown"], [class*="prose"], .message-content',
  );
  if (markdownEl) text = markdownEl.innerText || markdownEl.textContent;
  if (!text || text.length < 10)
    text = responseEl.innerText || responseEl.textContent;
  if (!text || text.length < 10) {
    const paras = responseEl.querySelectorAll("p, li, h1, h2, h3, h4, span");
    text = Array.from(paras).map((p) => p.innerText).join(" ");
  }

  if (!text || text.length < 10) {
    if (!isAuto) alert("Could not extract response text. Please try again.");
    return;
  }

  // Remove any existing panel
  const existing = wrapper.querySelector(
    ".llm-checker-panel, .llm-checker-limit-panel",
  );
  if (existing) existing.remove();

  btn.disabled = true;
  btn.innerHTML = "⏳ Checking...";
  const loadingPanel = createLoadingPanel();
  wrapper.appendChild(loadingPanel);

  chrome.runtime.sendMessage(
    { type: "VERIFY_RESPONSE", text: text.slice(0, 10000) },
    (response) => {
      if (chrome.runtime.lastError) {
        console.error("Runtime error:", chrome.runtime.lastError.message);
        loadingPanel.remove();
        btn.disabled = false;
        btn.innerHTML = `
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none"
               stroke="currentColor" stroke-width="2">
            <path d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"/>
          </svg>
          Cross-Check`;
        return;
      }

      loadingPanel.remove();
      btn.disabled = false;
      btn.innerHTML = `
        <svg width="14" height="14" viewBox="0 0 24 24" fill="none"
             stroke="currentColor" stroke-width="2">
          <path d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"/>
        </svg>
        Cross-Check Again`;

      if (response?.limitReached) {
        wrapper.appendChild(createLimitPanel(response));
        return;
      }

      if (response?.success) {
        const marks = highlightClaims(responseEl, response.results);
        const panel = createResultsPanel(response);
        if (marks.length > 0) {
          panel
            .querySelector(".llm-checker-close")
            .addEventListener("click", () => clearHighlights(marks));
        }
        wrapper.appendChild(panel);
      } else {
        const errorDiv = document.createElement("div");
        errorDiv.className = "llm-checker-error";
        errorDiv.textContent = `Error: ${response?.error || "Unknown error occurred"}`;
        wrapper.appendChild(errorDiv);
      }
    },
  );
}

// ── Watch a response element until streaming settles, then call onDone ───────
// Two code paths:
//   • Mutations seen → idleTimer fires 1500ms after last change → onDone()
//   • No mutations in 600ms → element was already complete → onDone() immediately
// onDone is always called exactly once.
function watchUntilStreamEnd(responseEl, onDone) {
  let idleTimer = null;
  let hasSeenMutation = false;
  let done = false;

  function finish() {
    if (done) return;
    done = true;
    streamObs.disconnect();
    onDone();
  }

  const streamObs = new MutationObserver(() => {
    hasSeenMutation = true;
    clearTimeout(idleTimer);
    idleTimer = setTimeout(finish, 1500);
  });

  streamObs.observe(responseEl, {
    childList: true,
    subtree: true,
    characterData: true,
  });

  // Element was already fully rendered before we started watching
  setTimeout(() => {
    if (!hasSeenMutation) finish();
  }, 600);
}

// ── Inject verify button into a response element ──────────────────────────────
function injectVerifyButton(responseEl) {
  if (responseEl.dataset.llmCheckerInjected === "true") return;

  // Walk up ancestors to check if any container for this message was already
  // processed. We mark containers with data-llm-checker-done at injection time,
  // so this catches cases where two different nested elements belong to the same
  // message (e.g. [class*="font-claude"] matching both outer and inner divs).
  let node = responseEl.parentNode;
  while (node && node !== document.body) {
    if (node.dataset && node.dataset.llmCheckerDone === "true") return;
    node = node.parentNode;
  }

  // Find the best named container to mark, so all children of this message
  // are covered by a single marker going forward.
  const messageContainer =
    responseEl.closest('[data-message-author-role="assistant"]') ||
    responseEl.closest('[data-testid="assistant-message"]') ||
    responseEl.closest("[data-response-id]") ||
    responseEl.closest("message-content") ||
    responseEl.parentNode;

  messageContainer.dataset.llmCheckerDone = "true";
  responseEl.dataset.llmCheckerInjected = "true";

  const btn = createVerifyButton();
  const wrapper = document.createElement("div");
  wrapper.className = "llm-checker-wrapper";
  wrapper.appendChild(btn);

  responseEl.parentNode.insertBefore(wrapper, responseEl.nextSibling);

  // Manual click always runs verify
  btn.addEventListener("click", () => runVerify(responseEl, wrapper, btn, false));

  // Auto-check: stream is already settled when injectVerifyButton is called,
  // so just trigger verify directly (small delay for DOM to fully stabilize).
  if (autoCheckEnabled && pageLoadComplete) {
    setTimeout(() => {
      if (!btn.disabled) runVerify(responseEl, wrapper, btn, true);
    }, 300);
  }
}

// ── Scan page for AI responses ────────────────────────────────────────────────
function scanForResponses() {
  const selectorList = SITE.isChatGPT
    ? SELECTORS.chatgpt
    : SITE.isGemini
    ? SELECTORS.gemini
    : SELECTORS.claude;

  for (const selector of selectorList) {
    const responses = document.querySelectorAll(selector);
    if (responses.length > 0) {
      let found = 0;
      responses.forEach((el) => {
        const text = el.innerText || el.textContent || "";
        if (text.trim().length > 20) {
          // Already injected or being watched — count it so we still break
          if (
            el.dataset.llmCheckerInjected === "true" ||
            el.dataset.llmCheckerWatching === "true"
          ) {
            found++;
            return;
          }
          // Skip if an ancestor is already handled or being watched
          let node = el.parentNode;
          while (node && node !== document.body) {
            if (
              node.dataset &&
              (node.dataset.llmCheckerDone === "true" ||
                node.dataset.llmCheckerWatching === "true")
            )
              return;
            node = node.parentNode;
          }
          // Mark as watching and wait for stream to settle before injecting
          el.dataset.llmCheckerWatching = "true";
          watchUntilStreamEnd(el, () => injectVerifyButton(el));
          found++;
        }
      });
      if (found > 0) {
        console.log(
          `LLM Checker: watching ${found} response(s) using selector: ${selector}`,
        );
        break;
      }
    }
  }
}

// ── MutationObserver — watches for new responses ──────────────────────────────
const observer = new MutationObserver(() => {
  clearTimeout(window.llmCheckerTimer);
  window.llmCheckerTimer = setTimeout(() => {
    scanForResponses();
  }, 800);
});

observer.observe(document.body, {
  childList: true,
  subtree: true,
});

// ── Load auto-check setting and react to changes from the popup ──────────────
function loadAutoCheckSetting() {
  chrome.storage.sync.get(["autoCheck"], (settings) => {
    autoCheckEnabled = settings.autoCheck === true;
    console.log("LLM Checker: autoCheck =", autoCheckEnabled);
  });
}

chrome.storage.onChanged.addListener((changes, area) => {
  if (area === "sync" && changes.autoCheck !== undefined) {
    autoCheckEnabled = changes.autoCheck.newValue === true;
    console.log("LLM Checker: autoCheck updated to", autoCheckEnabled);
  }
});

loadAutoCheckSetting();

// Initial scan — mark page load complete 1s after the scan so the auto-check
// guard only fires for responses that arrive after the page has settled.
setTimeout(scanForResponses, 1000);
setTimeout(() => { pageLoadComplete = true; }, 2000);
